services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: mainichi-nihongo
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE_TAG_NAME}:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SERVER_URL: ${SERVER_URL}
      GOOGLE_APPLICATION_CREDENTIALS: /credentials/mainichi-nihongo-460709-dbe1b498b089.json
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/api:/credentials:ro

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db_data: